### ISSUE TITLE
uninitialized constant AuthTrail::ApplicationJob

### ISSUE THREAD

**Issue by yoonwaiyan** [ankane/authtrail#4]
I have this error while running the install command `rails generate authtrail:install`. Is there anything I'm missing out(such as autoloading)? This project is using Ruby 2.4.2, Rails 5.0.2.

```
/Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/authtrail-0.1.0/app/jobs/auth_trail/geocode_job.rb:2:in `<module:AuthTrail>': uninitialized constant AuthTrail::ApplicationJob (NameError)
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/authtrail-0.1.0/app/jobs/auth_trail/geocode_job.rb:1:in `<top (required)>'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:475:in `each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:475:in `block in eager_load!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:473:in `each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:473:in `eager_load!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:354:in `eager_load!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:59:in `each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/railtie.rb:193:in `public_send'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/railtie.rb:193:in `method_missing'
	from /Users/waiyanyoon/Documents/workspace/project/config/environment.rb:5:in `<top (required)>'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/waiyanyoon/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by yoonwaiyan** [comment]
Nevermind, just found the issue of missing ApplicationJob because this Rails app is upgraded from older versions of Rails.

**Comment by ck2000** [comment]
I am getting the described error with rails 5.2.2.1. How can I solve this?

**Comment by ankane** [comment]
@ck2000 You need to a file in `app/jobs/application_job.rb` with:

```ruby
class ApplicationJob < ActiveJob::Base
end
```

In future version, I'll likely have the AuthTrail job inherit from `ActiveJob::Base` directly to avoid this.
