### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by evilsideburns** [ankane/authtrail#42]
All `AuthTrail::GeocodeJob` now raise `NotImplementedError` in my Sidekiq log.

Not sure how long they've been happening, I only just found them. But we did recently upgrade to Rails 6.1.3.2.

Even in the Rails console, `AuthTrail::GeocodeJob.new.perform` raises `NotImplementedError`.

Initializer just contains:

```
AuthTrail.geocode = true
AuthTrail.job_queue = :geocode
```

Authtrail gem is version `0.3.1`.

**Comment by ankane** [comment]
Hey @evilsideburns, can you paste the complete stack trace?

**Comment by evilsideburns** [comment]
```
I, [2021-07-01T07:06:41.859237 #24802]  INFO -- : [ActiveJob] [AuthTrail::GeocodeJob] [99dade4a-f606-47e7-b6f1-dede3766b89e] Performing AuthTrail::GeocodeJob (Job ID: 99dade4a-f606-47e7-b6f1-dede3766b89e) from Sidekiq(geocode) enqueued at 2021-07-01T07:02:14Z with arguments: #<GlobalID:0x0000000005cbd7e8 @uri=#<URI::GID gid://lux/LoginActivity/137060>>
E, [2021-07-01T07:06:41.859598 #24802] ERROR -- : [ActiveJob] [AuthTrail::GeocodeJob] [99dade4a-f606-47e7-b6f1-dede3766b89e] Error performing AuthTrail::GeocodeJob (Job ID: 99dade4a-f606-47e7-b6f1-dede3766b89e) from Sidekiq(geocode) in 0.19ms: NotImplementedError (NotImplementedError):
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:55:in `perform'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:48:in `block in perform_now'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.3/lib/airbrake/rails/active_job.rb:22:in `block in perform'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-ruby-5.2.0/lib/airbrake-ruby/benchmark.rb:13:in `measure'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.3/lib/airbrake/rails/active_job.rb:21:in `perform'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.3/lib/airbrake/rails/active_job.rb:45:in `block (2 levels) in <module:ActiveJob>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:21:in `block in instrument'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:31:in `instrument'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:22:in `block in tag_logger'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:22:in `tag_logger'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:47:in `perform_now'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:25:in `block in execute'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:84:in `wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:71:in `wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:23:in `execute'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activejob-6.1.3.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.3/lib/airbrake/sidekiq.rb:11:in `block in call'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-ruby-5.2.0/lib/airbrake-ruby/benchmark.rb:13:in `measure'
/var/www/production/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.3/lib/airbrake/sidekiq.rb:10:in `call'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:9:in `call'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:163:in `block in process'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112:in `local'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:14:in `block in call'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:71:in `wrap'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:13:in `call'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:257:in `stats'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13:in `call'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
/var/www/production/shared/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

**Comment by ankane** [comment]
Thanks. From what I can tell, it doesn't seem to be an issue with AuthTrail (could be similar to https://github.com/mperham/sidekiq/issues/4665).

**Comment by evilsideburns** [comment]
I feel silly now, but I went back to check it and it just now seems to be working. My `login_activities` now (mostly) have city, region, and country.
